// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHQeCV3OqqK7ravc96bFS8CQfZc8OOus',
    appId: '1:1000952327565:web:back_me_app',
    messagingSenderId: '1000952327565',
    projectId: 'back-me-3a5e5',
    authDomain: 'back-me-3a5e5.firebaseapp.com',
    storageBucket: 'back-me-3a5e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHQeCV3OqqK7ravc96bFS8CQfZc8OOus',
    appId: '1:1000952327565:android:87d7b73cc0cf9932c9e1c4',
    messagingSenderId: '1000952327565',
    projectId: 'back-me-3a5e5',
    storageBucket: 'back-me-3a5e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3419IeG9xpKQB_Y_XPjhR_stkovt2T3M',
    appId: '1:1000952327565:ios:148ee540a916da68c9e1c4',
    messagingSenderId: '1000952327565',
    projectId: 'back-me-3a5e5',
    storageBucket: 'back-me-3a5e5.firebasestorage.app',
    iosBundleId: 'com.backme.backme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3419IeG9xpKQB_Y_XPjhR_stkovt2T3M',
    appId: '1:1000952327565:macos:back_me_app',
    messagingSenderId: '1000952327565',
    projectId: 'back-me-3a5e5',
    storageBucket: 'back-me-3a5e5.firebasestorage.app',
    iosBundleId: 'com.backme.backme',
  );
} 